### PR TITLE
Fixed compiler error with esp idf version 4

### PR DESCRIPTION
**Pull request by 0xFEEDC0DE64**

### CODE REVIEW

**Comment by Makuna** [comment]
What environment are you using that requires this change?  This was added with with 4 in i2s_caps.h.

**Comment by 0xFEEDC0DE64** [comment]
I am using GCC 8.4.0 and idf version 4

**Comment by Makuna** [comment]
> I am using GCC 8.4.0 and idf version 4

Arduino IDE?
Check your i2s_caps.h for the presence of the missing symbol.

**Comment by 0xFEEDC0DE64** [comment]
Haven't tried the arduino ide, I am compiling from terminal always (also in the cloud using continuous integration). I am using platformio with the latest esp-idf and compiler. Do you need an example project to verify?

**Comment by 0xFEEDC0DE64** [comment]
I cant find any definition, is there a need for the version check at all in your code?

**Comment by Makuna** [comment]
When a standard system definition becomes available, it should be used.  This is just good coding practice.
It is present in my environment, I listed the file above.  I want to know why its not in yours.  Are you building a pure IDF rather than an Arduino ?

**Review by Makuna — APPROVED** [review]

**Pull request merged**
