### PR TITLE
Tm1814

### PR DESCRIPTION
**Pull request by Makuna**

### CODE REVIEW

**Comment by BlueAndi** [comment]
Regarding safekeeping, I did something similar using the brightness control: https://github.com/BlueAndi/esp-rgb-led-matrix/commit/e9c0875522e095bb9350173b9c6442fd6bc1a754

**Comment by wartron** [comment]
@Makuna 
This merge started breaking builds on my esp8266. 2.5.6 release from a few days earlier works tho.

```
In file included from C:\Users\willw\Documents\Arduino\esp\NeoPixelCylon\NeoPixelCylon.ino:10:0:

C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus\src/NeoPixelBus.h: In instantiation of 'typename T_COLOR_FEATURE::ColorObject NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::GetPixelColor(uint16_t) const [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x>; typename T_COLOR_FEATURE::ColorObject = RgbColor; uint16_t = short unsigned int]':

C:\Users\willw\Documents\Arduino\esp\NeoPixelCylon\NeoPixelCylon.ino:43:47:   required from here

C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus\src/NeoPixelBus.h:232:64: error: passing 'const NeoPixelBus<NeoGrbFeature, NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x> >' as 'this' argument of 'uint8_t* NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::_pixels() [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x>; uint8_t = unsigned char]' discards qualifiers [-fpermissive]

             return T_COLOR_FEATURE::retrievePixelColor(_pixels(), indexPixel);

                                                                ^

Multiple libraries were found for "SPI.h"
 Used: C:\Users\willw\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SPI
Multiple libraries were found for "NeoPixelBus.h"
 Used: C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
````

**Comment by Makuna** [comment]
> @Makuna
> This merge started breaking builds on my esp8266. 2.5.6 release from a few days earlier works tho.
> In file included from C:\Users\willw\Documents\Arduino\esp\NeoPixelCylon\NeoPixelCylon.ino:10:0:
> 
> C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus\src/NeoPixelBus.h: In instantiation of 'typename T_COLOR_FEATURE::ColorObject NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::GetPixelColor(uint16_t) const [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x>; typename T_COLOR_FEATURE::ColorObject = RgbColor; uint16_t = short unsigned int]':
> 
> C:\Users\willw\Documents\Arduino\esp\NeoPixelCylon\NeoPixelCylon.ino:43:47:   required from here
> 
> C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus\src/NeoPixelBus.h:232:64: error: passing 'const NeoPixelBus<NeoGrbFeature, NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x> >' as 'this' argument of 'uint8_t* NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::_pixels() [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x>; uint8_t = unsigned char]' discards qualifiers [-fpermissive]
> 
>              return T_COLOR_FEATURE::retrievePixelColor(_pixels(), indexPixel);
> 
>                                                                 ^
> 
> Multiple libraries were found for "SPI.h"
>  Used: C:\Users\willw\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SPI
> Multiple libraries were found for "NeoPixelBus.h"
>  Used: C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus
> exit status 1
> Error compiling for board NodeMCU 1.0 (ESP-12E Module).

Please create an issue, closed and merged code is not the place to raise the problem, referencing it is ok.

**Comment by Makuna** [comment]
> @Makuna
> This merge started breaking builds on my esp8266. 2.5.6 release from a few days earlier works tho.
> In file included from C:\Users\willw\Documents\Arduino\esp\NeoPixelCylon\NeoPixelCylon.ino:10:0:
> 
> C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus\src/NeoPixelBus.h: In instantiation of 'typename T_COLOR_FEATURE::ColorObject NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::GetPixelColor(uint16_t) const [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x>; typename T_COLOR_FEATURE::ColorObject = RgbColor; uint16_t = short unsigned int]':
> 
> C:\Users\willw\Documents\Arduino\esp\NeoPixelCylon\NeoPixelCylon.ino:43:47:   required from here
> 
> C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus\src/NeoPixelBus.h:232:64: error: passing 'const NeoPixelBus<NeoGrbFeature, NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x> >' as 'this' argument of 'uint8_t* NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::_pixels() [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeedWs2812x>; uint8_t = unsigned char]' discards qualifiers [-fpermissive]
> 
>              return T_COLOR_FEATURE::retrievePixelColor(_pixels(), indexPixel);
> 
>                                                                 ^
> 
> Multiple libraries were found for "SPI.h"
>  Used: C:\Users\willw\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SPI
> Multiple libraries were found for "NeoPixelBus.h"
>  Used: C:\Users\willw\Documents\Arduino\libraries\NeoPixelBus
> exit status 1
> Error compiling for board NodeMCU 1.0 (ESP-12E Module).

pick up the lates merge should fix it.

**Pull request merged**
