### PR TITLE
Esp32 Fixes

### PR DESCRIPTION
**Pull request by Makuna**
Fix improper ifdef/else/endif
DRAM_ATTR on ISR const data
ISR allows LEVEL1 int

### CODE REVIEW

**Comment by BlueAndi** [comment]
Could we use prio 2?

**Comment by Makuna** [comment]
@BlueAndi I don't have the tests that would confirm if pri 2 or even pri 3 will work well with wifi.  If you wish to give it a try and push wifi hard enough to know what issues appear I will review your findings and change the default.

**Comment by BlueAndi** [comment]
Would running iperf be ok for you? I will integrate it and see how the display behaves. We can compare the determined bandwith, first with prio1 and 2nd. with prio2.

**Comment by BlueAndi** [comment]
### RMT ISR with prio1:
**Linux console output:**
grafik
**Target console output:**
```
accept: 192.168.1.41,52580

        Interval Bandwidth
   0-   3 sec       4.78 Mbits/sec
   3-   6 sec       5.13 Mbits/sec
   6-   9 sec       5.08 Mbits/sec
   9-  12 sec       5.10 Mbits/sec
  12-  15 sec       5.07 Mbits/sec
  15-  18 sec       5.09 Mbits/sec
  18-  21 sec       5.07 Mbits/sec
  21-  24 sec       5.10 Mbits/sec
  24-  27 sec       5.08 Mbits/sec
  27-  30 sec       5.10 Mbits/sec
   0-  30 sec       5.06 Mbits/sec
```

### RMT ISR with prio2:
**Linux console output:**
grafik
**Target console output:**
```
accept: 192.168.1.41,52482

        Interval Bandwidth
   0-   3 sec       5.06 Mbits/sec
   3-   6 sec       5.08 Mbits/sec
   6-   9 sec       5.14 Mbits/sec
   9-  12 sec       5.04 Mbits/sec
  12-  15 sec       5.09 Mbits/sec
  15-  18 sec       5.09 Mbits/sec
  18-  21 sec       5.09 Mbits/sec
  21-  24 sec       5.02 Mbits/sec
  24-  27 sec       5.09 Mbits/sec
  27-  30 sec       5.05 Mbits/sec
   0-  30 sec       5.08 Mbits/sec
```

**Comment by BlueAndi** [comment]
Looks like there is no significant influence.

**Comment by Makuna** [comment]
@BlueAndi Try Pri3?

**Comment by BlueAndi** [comment]
### RMT ISR with prio 3:
**Linux console output:**
grafik
**Target console output:**
```
accept: 192.168.1.41,53932

        Interval Bandwidth
   0-   3 sec       4.74 Mbits/sec
   3-   6 sec       4.72 Mbits/sec
   6-   9 sec       4.76 Mbits/sec
   9-  12 sec       4.78 Mbits/sec
  12-  15 sec       4.75 Mbits/sec
  15-  18 sec       4.75 Mbits/sec
  18-  21 sec       4.74 Mbits/sec
  21-  24 sec       4.77 Mbits/sec
  24-  27 sec       4.74 Mbits/sec
  27-  30 sec       4.77 Mbits/sec
   0-  30 sec       4.75 Mbits/sec
```

**Comment by BlueAndi** [comment]
Note, in a 2nd try with prio 3, I got
grafik

For me again, no significant change. But I am not a expert in stress testing. :-)

**Pull request merged**
